language: php
php:
  - 7.1.9
script:
  - cd tests

before_deploy:
- echo '{"require" : {
    "silex/silex": "^2.0.4",
    "monolog/monolog": "^1.22",
    "twig/twig": "^2.0",
    "symfony/twig-bridge": "^3"
  }}' > composer.json
deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: phpget
